ivoa-std/ivoatex

Makefile

This is partially taken from [jdswinbank/vtp](https://github.com/jdswinbank/vtp/blob/master/Makefile); however I applied the change to the ivoatex repository instead of each individual document repository.
The SVN tags in the individual document repositories have no use anymore and should be removed.
Calling @msdemlei for a review. This should still work with SVN.

Replace the SVN repository variables with their git equivalents

---

.gitignore

This means that when you build the html document (which in turn
builds tth) it doesn't look like your ivoatex submodule is modified.

add .gitignore to ignore tth_C/tth

---

Makefile
submission.py

Someone had already started to move ivoatex submission.py to python3.
This hopefully completes this (at least it's worked for the upload of the UCD list)

Completing python3 migration of submission.py

---

Makefile
draft-background.tex

Run  "make mydocname-draft.pdf" to have a watermark, which is defined
in draft-background.tex.
This is mainly in response to requirements from people doing CI.

Adding a facility to build watermarked PDFs.

---

Makefile
fetch_from_ads.py

We're pulling the records for our document repository bibliography from ADS.  As ADS' "classic" interface was retired, our old and simple method of building this bibliography broke.  In particular, we now need an ADS token, and there's a bit more json manipulation involved, so I'm afraid we have to migrate to a bit of python to pull the bibliography.

Update docrepo.bib making

---

Makefile
draft-background.tex
fetch_from_ads.py

This PR improves building a document in two ways:
(a) make forcetex now does what people expect in their CI code: it
rebuilds the document as if the TeX source had changed.  In contrast, up
to now the dependencies didn't get built with forcetex.
(b) If available, latexmk is now used to build the document.  That ought
to save a lot of the resons to run forcetex in the first place.

Latex build fixes

---

docrepo.bib
ivoabib.bib
svn-ignore.txt

The bulk of this PR is just the effect of make docrepo.bib.
This is large this time around because this is now make through the new
ADS.  Future updates should be limited to the records actually changed again.
Don't feel obliged to review this too much -- I'll force-merge tomorrow if nobody looks, as this is really totally technical.
There are also a few BibTeX markup fixes to the manual bibliography (ivoabib.bib).
And, because it's so trivial, I dare throw in two extra ignore patterns we need when latexmk is in use.

Updating docrepo.bib

---

Makefile
README.rst
github_workflow_build.yml.template
github_workflow_preview.yml.template

This task will add 2 hidden files configuring the GitHub repository so that
a PDF preview is generated when a commit is pushed and when a PullRequest is
updated with commits. In the first case, the PDF preview will be published
in a GitHub Pre-Release (and will have a fix URL). In the second case, the PDF
will be accessible as a check artefact through the `Checks` tab of the
PullRequest.
The task `github-preview` will create two YAML files inside the directory
`.github/workflows/`:
- `build.yml`   - workflow triggered at each PullRequest
- `preview.yml` - workflow triggered at each pushed commit
Both files have to be commited and push to a remote GitHub repository to enable
the corresponding GitHub workflows.

Add Makefile task `github-preview`

---

Makefile
github_workflow_build.yml.template
github_workflow_preview.yml.template

For one, we now install latex-mk (more robust building) and cm-super (T1
fonts for better output and faster runtime because no metafont needs to
be run).
And we fix the slightly dumb non-latexmk rule of failing when a process
with suppressed output fails.  What was I thinking?

CI improvement.

---

tth-ivoa.xslt
tth_C/tth.c

This, for one, make it stop call covert for role diagrams (no spurious
role_diagram.png any more, to issues with libsvg for convert).  This also
makes the ugly XSLT rule turning the png back into the svg superfluous.
A side effect: you can use svgs for other images in ivoatex documents.
I should advertise that in ivoatexDoc.
(I've asked tth upstream to accept that diff, too, so we don't diverge from them).

Teaching tth to accept .svg as a valid image file for browsers.

---

tthdefs.tex

I should have defined it like this from the start, but I didn't dare try it because TeX would immediately reject such a thing (you need to fix catcodes before parsing the argument).  This even works with matched-up braces...  amazing.
This ought to fix the bug underlying https://github.com/ivoa-std/ConeSearch/pull/49 and obviate the need for the PR.
(Where I'd say we could still apply the PR, as the formatting improvements are probably worth it)

Gung-ho definition of nolinkurl

---

Makefile

(where I can't quite explain why Grégory's echo didn't need the -e)

github-preview info messages now expand their escapes.

---

archdiag-full.xml

I've had to shift around boxes quite a bit to make things fit.  It's
getting tight in that magic area of bespoke tabular structures (obscore,
epn-tap, obsloctap), which we've put between DM and DAL so far.  Hm...

Adding EPN-TAP and ObsLocTAP to the architecture diagramme.

---

CHANGES
ivoabib.bib

This will *break existing documents* (which is why I've left these records in so far).  
On the other hand, these documents probably should have moved to taking the references from docrepo.bib anyway.  With this change, they will note that.  This will also address recurring trouble as exhibited last in Issue #25.
Since this is document-breaking, I will only merge this if I have two positive review and nobody opposing.

Removing IVOA standards and ADS-published documents from ivoabib.

---

Makefile
Makefile.template
tth-ivoa.xslt

This PR does two things:
(a) it changes the makefile template so that the ivoatex submodule
(and potentially any others) will automatically be initialised
if people forgot to do the recurse-submodules (which ought to address
issue #27).
(b) it adds an "update" target to the ivoatex makefile so people can
say "make update" now and then to fetch the latest ivoatex.
A review by people who've thought more about git submodules than I have
would be highly appreciated.

 More gracefully deal with submodules

---

tth-ivoa.xslt

(In HTML)
The most intrusive change here is that the HTML document body width
will now be restricted to 21cm -- that's already too much for my taste, but
it keeps things remotely readable when people have their browser fullscreen.
Also, this commit recovers the style of the architecture diagram.
This is based on an xslt hack right now rather than trying
to declare a css class in the LaTeX, because there's no facility
for the latter at this point.  It's something we might want to have for other
figures one of these days, though.

Control the width of the main document and the architecture diagram 

---

make-archdiag.xslt

*Not to be merged for now*
The architecture diagrams produced by ivoatex give all boxes the same
width.  That yields a nicely regular appearance but wastes a lot of
space.  And arch diag real estate begins to run short.
Now, I've not found a way to just draw a box around some text in plain
svg.  To see if this is something we'd even want, I've created a JS
simulation of what I'd like to have.
Discussion on this preferably on the IVOA stdproc mailing list; see http://mail.ivoa.net/pipermail/stdproc/2021-January/000110.html

Fit archdiag boxes to text width

---

tth-ivoa.xslt
tthdefs.tex

The default caption rendering of tth is really ugly.  This PR
makes it stylable (using something that is, indeed, a bit of a hack
I don't like too much either, but it looks robust enough).
It also adds a light style.
Furthermore, I'm using this to sneak in a whitespace normalisation for
tth-ivoa.xslt, so be sure to look at .patch rather than .diff.

Improve caption html

---

Makefile

.DELETE_ON_ERROR might be a GNU extension (I've not researched), but even if there's ever some other make processing this, it at least shouldn't hurt.
Quoting GNU make's info pages:
> This is almost always what you want 'make' to do, but it is not historical practice; so for compatibility, you must explicitly request it.
While I'm at changing the makefile, I'm also changing the CSS href for the HTML rendering to https.  That shouldn't be necessary when ivoa.net properly gives sets up a content-security-policy, and clearly it would save a bit if effort when coming from somewhere else, but overall it's probably less hassle this way.

Telling make to delete targets of failed builds.

---

submission.py

The IVOA docrepo upload form didn't understand PEN and EN so far.  It does now, so we can drop the hack working around that.

Removing EN/PEN upload hack

---

github_workflow_preview.yml.template

Update the tag name and message for the GitHub Action
[Walking Tag](https://github.com/marketplace/actions/walking-git-tag)
accordingly to its last version. This make disappear the warning message about
the former `TAG_NAME` and `TAG_MESSAGE`.
_See the Walking-Tag's [commit 5242039](weareyipyip/walking-tag-action@5242039)
for more details about this change._

[CI] Update the template for the GitHub Workflow "PDF Preview".

---

README.rst
document.template
ivoa.cls
ivoabib.bib
schemadoc.xslt
stdrec-template.xml
svn-ignore.txt
tth-ivoa.xslt
tthdefs.tex

This PR moves quite a few links into the IVOA web page to https.
While in principle, people are redirected, setting the links properly
saves one redirect.  In the case of the CSS references, having
them point to https directly saves us from having to rely on
upgrade-insecure-requests for having CSS when the documents are
requested via https.
I'm sneaking in to really minor-impact unrelated commits: for one, ivoatex-produced html so far has been missing body tags, and the svn-ignore.txt template now also ignores gitmeta.tex, which is going to help a lot.  I'd hate to have to write dedicated PRs for these two little things.

Move to https links

---

Makefile
archdiag-full.xml
make-archdiag.xslt

This PR makes the arch diagram use variable-width boxes.
This opens up a lot of space for further arch diagram growth at the expense of making it appear somewhat less orderly.
This should be backwards-compatible with existing documents (that will still use constant-width boxes).  The process of adding boxes is now a bit more difficult – see archdiag-full.xml for more info.

Adding widths and some infrastructure to get them to the arch diagram

---

make-archdiag.xslt

With what's in ivoatex right now, thisrec for variable-width boxes is off-center
(unless the box happens to be 90 pixel wide).

Make the thisrec ellipse center on variable-width boxes.

---

ivoa.cls
tthdefs.tex

Apart from a bit of uniform markup, this in particular enables breaking
UCDs at semicolons and dots.  As a side effect, atoms can be hyphenated,
too.
If this is merged, the corresponding definitions in EPN-TAP should be
removed; UCDList's ucd macro is different (at least for now) and probably
should stay that way because of the special requirements in UCD presentation
there.

Adding a ucd macro.

---

.gitignore
Makefile

I'm sneaking in a .gitignore amendment for ignoring vi swap files, too.

Amending make clean target for latexmk (and ignoring vi swap files)

---

svn-ignore.txt

This is because it's really cheap to remake (nothing will work without
xsltproc anyway).
Using the opportunity to also ignore gvim swap files.

Now ignoring role-diagram.svg by default

---

make-archdiag.xslt

For the rationale, see https://css-tricks.com/scale-svg/

Using viewBox rather than width and height in the role diagram SVG now

---

svn-ignore.txt

As a minor convenience, ignore the `.DS_Store` files that Macs sometimes put in directories when they've been browsed with the `Finder` application.
Side question:  While in `svn-ignore.txt`, I noticed `role_diagram.svg` and `*.pdf`.  Those seem in conflict with the current guidance of including `role_diagram.svg` and `role_diagram.pdf` in the repository as a work-around to the `inkscape` build dependency.  Depending on how long that guidance will be in place, would it make sense to replace the `role_diagram.svg` line (allow that file) with `!role_diagram.pdf` (explicitly allow that pdf while still ignoring all others)?

Ignore Mac .DS_Store files

---

CHANGES
Makefile

I hope with this we can stop including build artefacts (role_diagram.pdf)
by default when rsvg is easily available on the relevant platforms.

Use rsvg rather than inkscape for SVG->PDF conversion.

---

.gitignore
Makefile
README.rst
suggest-bibupgrade.py

The idea of this change is that people can, when re-uptaking a document
or before submission, say
make bib-suggestions
and the machine will tell them for which documents there are newer versions.  This is based on a hand-curated list; one day in the future we may be able to automate its generation, but for now it's probably not much effort to maintain that mapping.
Automatic fixes of the citations are quite certainly too dangerous, as we may have version-sharp references.
The stuff may be a bit more helpful if it wouldn't just put in the bibcodes; but since that would entail searching and formatting bibtex records, I'd first like to see folks clamour for that.

Add bibupgrade

---

ivoa.cls

This is because mangled quotes may look nice but don't work when
people cut and paste.

Setting upquote lst option by default.

---

ivoa.cls

This is required for the upquote option to lstlistings on older
installations.

Requiring textcomp, too.

---

archdiag-full.xml

I also have an alternate Makefile to generate arch diagrams in pdf format because I can't see what make command would do that with the normal Makefile. Am I missing something? Should I include that file for convenience? it has:
```
ivoatex[master]>cat Makefile.arch 
include Makefile
archdiag2.svg: archdiag-full.xml make-archdiag.xslt
$(XSLTPROC) -o $@ make-archdiag.xslt archdiag-full.xml
```
and is used as
```
make -f Makefile.arch archdiag2.pdf
```

change GMS from prerec to rec

---

Makefile

That's necessary to keep ivoatex from getting stuck at the original commit.
Oh my -- talk about a somewhat odd default.

make update will now rebase ivoatex.

---

tth_C/CHANGES
tth_C/tth.c
tthdefs.tex

This contains two of our own patches (svn, nolinkurl).  The nolinkurl
part can hence go from tth-ivoa.tex.
Since we are about it, I've included yet another change (which is actually minor, but produces a large patch because of code generation), which brings this to tth 4.16.  This particular change fixes bug #85.

Updating tth to upstream 4.16.

---

schemadoc.xslt
tth_C/tth.c
update_generated.py

These commits fix two unrelated bugs I noticed while processing StandardsRegExt, one concerning HTML formatting (rather new and hitting everyone), one concerning formatting of schema documentation (ancient and having so far not concerned anyone).

Fixes for standardsregext

---

tth_C/tth.c

Without this, you will have a #! at the TOP of what's built for HTML.

Fixing the declaration of nolinkurl in upstream tth.

---

tth-ivoa.xslt

The old fixed size didn't work terribly well across various browser widths. The new choice of 38% makes for a golden section between the box and the main text.  Ha!

Improving width of admonition boxes in HTML

---

update_generated.py

This lets you say something like 
```
% GENERATED: !vocterms voresource/date_role
% /GENERATED
```
and you will get a list of terms in the named vocabulary from the IVOA doc repo into your document.
Admittedly, it is questionable whether standards should do this given vocabularies can and should be added to.  But informational lists of current terms were requested multiple times in document reviews, so let's at least make them convenient.

Adding vocterms generator function

---

ivoa.cls

I don't think any of its facilities are (or should be) used by modern IVOA specs.  And it has caused #97.

Dropping doc.sty as a requirement for ivoa.cls.

---

docrepo.bib

I use this reference in the UCD1+ 1.5 specification. 
I noticed this specification is not yet in docrepo.bib  .
thanks for your update . ML

added EPN-TAP reference from ADS to docrepo.bib

---

tth_C/tth.c

Without this, tth stack-smashes even with just a few lines of author list and my natbib hack.  With this larger buffer, that'll only happen with a few pages of authors.
Since tth doesn't play games with privileges and in an ivoatex context, people can run whatever code anyway, I'd say that's acceptable, at least until upstream plugs the overwrite as such.

Enlarging a TTH scratch buffer.

---

CHANGES
Makefile.template
archdiag-full.xml
fetch_from_ads.py
fromivoadoc.xslt
github_workflow_build.yml.template
github_workflow_preview.yml.template
ivoa.bst
ivoa.cls
ivoabib.bib
make-archdiag.xslt
schemadoc.xslt
stdrec-template.xml
submission.py
suggest-bibupgrade.py
tth-ivoa.xslt
tth_C/tth.c
tth_C/tthsplit.c
tthntbib.sty
vo-dml2ivoatex.xslt

...in everything that remotely looks like text.  This is because Markus' editor now swallows trailing blanks.  This commit should help avoid poisoning many future commits with spurious whitespace diffs.

WHITESPACE: nuking trailing blanks

---

tthdefs.tex

Macros whose definitions include newlines for cosmetic reasons can in some cases result in unwanted significant whitespace in HTML output. This addresses issue #115 as advised by @msdemlei; for \specialterm, \todo and \ivoatex by allowing long lines in the LaTeX source to avoid the line break, and for \auxiliaryurl by stripping cosmetic whitespace at the start of a line after a "%" character at the end of the previous line (since otherwise in that case the source line would get very long).
I've tested that this fix has the desired effect for \specialterm (via \xmlel in DALI), but not for the others.

Fix some whitespace issues in macros

---

ivoa.bst
test/test-ivoa-bst-urls.aux
test/test-ivoa-bst-urls.bib
test/test-ivoa-bst-urls.good
test/test-ivoa-bst-urls.sh

The two commits here fix errors in the previous attempt to update `ivoa.bst` to accommodate DOIs, which became manifest when this was tried with the VOUnits.tex file.  See the commit notes for details.

Fix url formatting

---

suggest-bibupgrade.py

I'd appreciate a critical view; I suppose I should add functionality to the script to see if the titles of the pairs roughly conincide...

Adding old-new pairs in bib-suggestions for 2022 and 2023

---

tth_C/UPDATING
tth_C/tth.c

Of course, it's not hard to craft TeX documents that will crash this, too. But tth is not a security boundary here, so I am about as unconcerned about its exploitability as upstream.

Bloating tth buffers a bit to prevent crashes on arm64.

---

Makefile.template
document.template
regressiontest/README.rst
regressiontest/run-regression.py

ivoatex could record the repo URI (in SVN) or the commit id (in git) on the document front page forever, but too few documents actually are actually using that right now.  As a remedy, this commit makes using this information the default in the templates.
A downside is that documents not under version control cannot be built out of the box (people first need to remove the \input gitmeta from their document and the gitmeta.tex dependency in the Makefile).  But people who cannot figure that out probably don't actually want to do that, and so a build failure may actually be an advantage in that it uncovers an actual mistake earlier.

gitmeta inclusion is now in the templates

---

Makefile
ivoa.cls
tthdefs.tex

Admittedly it would be a lot cooler if tth could produce inline svgs from tikz.  But that's totally utopian.
With the facilities here, at least things work, and the graphics end up scalably in both HTML and PDF.
This goes together with ivoatex PR 40.
And yes, I realise I'm not covering this with a regression test.  I promise I'll add one once the first IVOA document not written by me has a TikZ image (I'm not holding my breath, although TikZ is of course brilliant).

Support for tikz images in pdf and html

---

update_generated.py

This is not so much to make them clickable; the problem is that these URIs will not be broken by LaTeX if not marked up as URIs.  With the markup (and the breaklink option that ivoatex has), there's much fewer URIs sticking out of generated text -- and that's relevant because these overfull boxes cannot be manually fixed.

Trying to guess and format URLs in schmemadoc-generated source.

---

Makefile
regressiontest/run-regression.py

While historic practices have been varying, by now it is decided that notes live in a Notes subdirectory.

Updating base URL computation for notes.

---

github_workflow_build.yml.template
github_workflow_preview.yml.template

A missing `\` skipped the installation of pdftk, xsltproc, latexmk and cm-super.
This commit should fix this problem.
_Problem mentioned in https://github.com/ivoa-std/DALI/pull/45 and in #140_

Fix installation of dependencies

---

Makefile

Add a line checking that the git command is present, i.e. the make will fail if it's not.  Prevents silent production of an uninformative gitmeta.tex file in absence of git.
Absence of git may seem like an unlikely eventuality for an ivoatex build, but it has happened when building documents from docker.

check git is available in gitmeta.tex target

---

Makefile

This is because the preview workflow sets and moves a tag auto-pdf-preview that will keep conflicting when people have longer-lived checkouts.

On make tag, only push the newly-made tag now.

---

ivoa.cls

This is after the VOResource 1.2 DAL review that rightly pointed out that a Note-type box ended up at a confusing position.

Now prefering here-positioning for admontion floats.

---

Makefile

When making gitmeta.tex, we now test for git by running a short log. At least sometimes, this want to enter a pager, which is unwelcome when running make.  The extra -P switch prevents that.

git existence check no longer opens a pager.

---

ivoa.cls
tthdefs.tex

We now have enough documents wanting to mark up terms from vocabularies that ivoatex should have that feature (lifted from VocInVO2).
This PR adds it.  It is a bit more complicated than ordinary semantic markup because we want to enable hyphenation when terms are used with prefixes, as is usual with non-IVOA vocabularies ("foaf:person").  I think the savings in typographic hassle are worth the extra TeX code.

Adding a vocterm macro

---

github_workflow_preview.yml.template

I don't have a deep understanding of the CI here, but making a change equivalent to this fixed a preview build failure for AuthVO, so I guess the same edit should be in place in the upstream template.

add apt update to preview action template
