archdiag-full.xml
ivoa.cls
ivoabib.bib
make-archdiag.xslt
schemadoc.xslt
stdrec-template.xml
tth-ivoa.xslt
update_generated.py

This is a wrapup of various changes that accumulated in volute ivoatex
since github ivoatex was forked.  If this is merged, the two should
be in sync again.
See the individual commits for the various, mostly minor changes.
@pdowler: There are also some changes to the arch diagram.  If you'd
like to have a different upstream for the archdiag machinery, let me
know and I'll adjust ivoatex accordingly.

Volute ports

---

README.rst

Frankly, I feel a bit silly to create a PR for that...

Updating readme for automatic CI recipe add

---

stdrec-template.xml

(this is essentially editorial in nature, which is why I take the liberty of merging it with my own blessing)

Updating vocabulary-related info in sample VOResource record.

---

github_workflow_build.yml.template
github_workflow_preview.yml.template

Added commentary text to the top of the workflow templates to indicate where they came from and how to install them into a new ivoatex document repository.

Issue 28 template comentary

---

document.template

This is just a consequence of the PR #26.

updating VO architecture reference in the template

---

tthdefs.tex

(this is a bit of a brown bag matter)

making nolinkurl definition in tthdefs actually produce XML.

---

tthdefs.tex

This, really, is trivial.  I'll just merge it after some grace period.

tthdefs now knows about the scfigure environment.

---

tth-ivoa.xslt

Proposed endorsed notes and endorsed notes so far used the styles of
notes, with is not quite appropriate.
This PR will use the brand-new EN and PEN styles as applicable (many
thanks to Marco for producing those!)

Fixing backdrops/styles for EN/PEN

---

docrepo.bib

This is adding the UDF note, and then there's a bit of whitespace
noise coming down from ADS.  Let's hope they won't revert it.

Updating the bibliography from ADS.

---

archdiag-full.xml

shuffled some DM and GWS boxes
swapped ConeSearch and TAP so the Simple protocols are grouped at the top

added Meas, Coords, and Transform

---

submission.py

needed for the upload mechanism

added Operations to "wg" mapping

---

docrepo.bib

This in particular fixes the problem addressed by PR #49; Andrea's name
is now also updated in ADS.

Updating bibliography from ADS.

---

ivoabib.bib

Add HTTP Caching RFC to ivoabib

---

CHANGES
Makefile
README.rst

Also, completing the changelog and some editorial work on the README.

Bumping version to 1.2.

---

archdiag-full.xml

Moved Meas & Coords to REC.
Moved EPN-TAP to REC.
Moved ObsLocTAP to REC
Changed Model Annotation to MIVOT (and squeezed its box).

updated a few REC details

---

update_generated.py

(and dropping trailing whitespace in there)

Late python3 fix in update_generated.

---

ivoabib.bib

I need this for DocRegExt, and since it is a note, I thought it might as well live in ivoatex rather than in local.bib.

Add edumatters note

---

ivoabib.bib

We have not defined that in our bst, and I'm not so wild about citing web pages as to think about a good way to do that.  If you have to cite web sites, I suppose writing that into howpublished is as good as about anything else short of minting DOIs for them.
Also, dropping a record that's really too incomplete, and fixing a few minor typos in ivoabib.

Expunging @webpage from ivoabib.

---

tth_C/UPDATING
tth_C/tth.c

This restores the effect of PR #104.

Restoring TTH scratch buffer emergency hack.

---

aas_macros.tex
ivoa.cls
tthdefs.tex

Adding AASTeX journal macros.

---

submission.py

You definitely don't want to install python-requests from pypi:-).
Let's see what @nxg thinks about this...

Updating submission.py message for missing requests.

---

Makefile

I'm not sure very many people will *try* ``make help``.  But once they know about it it might come in handy.

Adding a help target explaining a few common targets

---

docrepo.bib

This is what make docrepo.bib changes right now.
Given there's a bunch of new DOIs, I think this warrants an update.

Update docrepo from ADS

---

Makefile
Makefile.template

(I'm skipping 1.4 in order to be in sync with ivoatexDoc)

Minor fixes towards release 1.5.

---

regressiontest/run-regression.py
stdrec-template.xml
update-stdrec.py

Also, minor fixes to the template record.
This is after recent experiences where one necessary changes was missed.  And I figured it's better to automate this than to write another checklist.

Adding a script to automate StdRegExt record updates.
